app:
  env: development
  kafka_topic: user-transactions

fin_api:
  http_host: 0.0.0.0
  http_port: 8080
  grpc_host: 0.0.0.0
  grpc_port: 9090
  grpc_target: fin-api:9090

fin_analytics:
  http_host: 0.0.0.0
  http_port: 8081

postgres:
  host: postgres
  port: 5432
  user: fintrack
  password: fintrack
  dbname: fintrack
  sslmode: disable

redis:
  host: redis
  port: 6379
  db: 0

kafka:
  brokers:
    - kafka:9092
  group_id: fin-analytics-group

